# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1500, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_start_judge = QtWidgets.QPushButton(self.centralwidget)
        self.button_start_judge.setEnabled(True)
        self.button_start_judge.setGeometry(QtCore.QRect(60, 210, 220, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_start_judge.setFont(font)
        self.button_start_judge.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(190, 184, 171);\n"
"    border-radius: 20px;\n"
"    border: 1px groove gray;\n"
"    border-style:outset;\n"
"}\n"
"QPushButton:disabled {\n"
"    color:#fff;\n"
"    background:#ccc;\n"
"    border-radius: 20px;\n"
"    border: 1px solid gray;\n"
"    border-style:outset;\n"
"}")
        self.button_start_judge.setObjectName("button_start_judge")
        self.button_choose_video = QtWidgets.QPushButton(self.centralwidget)
        self.button_choose_video.setGeometry(QtCore.QRect(60, 130, 220, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_choose_video.setFont(font)
        self.button_choose_video.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(190, 184, 171);\n"
"border-radius: 20px;\n"
"border: 1px groove gray;\n"
"border-style:outset;")
        self.button_choose_video.setObjectName("button_choose_video")
        self.label_video_name = QtWidgets.QLabel(self.centralwidget)
        self.label_video_name.setGeometry(QtCore.QRect(70, 10, 380, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_video_name.setFont(font)
        self.label_video_name.setScaledContents(True)
        self.label_video_name.setWordWrap(True)
        self.label_video_name.setObjectName("label_video_name")
        self.label_interrupt_times = QtWidgets.QLabel(self.centralwidget)
        self.label_interrupt_times.setGeometry(QtCore.QRect(70, 70, 380, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_interrupt_times.setFont(font)
        self.label_interrupt_times.setScaledContents(True)
        self.label_interrupt_times.setWordWrap(True)
        self.label_interrupt_times.setObjectName("label_interrupt_times")
        self.list_widget_interrupt = QtWidgets.QListWidget(self.centralwidget)
        self.list_widget_interrupt.setGeometry(QtCore.QRect(110, 440, 270, 371))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.list_widget_interrupt.setFont(font)
        self.list_widget_interrupt.setObjectName("list_widget_interrupt")
        self.button_check_result = QtWidgets.QPushButton(self.centralwidget)
        self.button_check_result.setEnabled(True)
        self.button_check_result.setGeometry(QtCore.QRect(60, 300, 220, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_check_result.setFont(font)
        self.button_check_result.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(190, 184, 171);\n"
"    border-radius: 20px;\n"
"    border: 1px groove gray;\n"
"    border-style:outset;\n"
"}\n"
"QPushButton:disabled {\n"
"    color:#fff;\n"
"    background:#ccc;\n"
"    border-radius: 20px;\n"
"    border: 1px solid gray;\n"
"    border-style:outset;\n"
"}")
        self.button_check_result.setObjectName("button_check_result")
        self.button_remove_interrupt = QtWidgets.QPushButton(self.centralwidget)
        self.button_remove_interrupt.setGeometry(QtCore.QRect(410, 770, 170, 35))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_remove_interrupt.setFont(font)
        self.button_remove_interrupt.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"border: 1px groove gray;\n"
"border-style:outset;")
        self.button_remove_interrupt.setObjectName("button_remove_interrupt")
        self.button_import_result = QtWidgets.QPushButton(self.centralwidget)
        self.button_import_result.setGeometry(QtCore.QRect(340, 210, 220, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_import_result.setFont(font)
        self.button_import_result.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(190, 184, 171);\n"
"border-radius: 20px;\n"
"border: 1px groove gray;\n"
"border-style:outset;\n"
"")
        self.button_import_result.setObjectName("button_import_result")
        self.label_done = QtWidgets.QLabel(self.centralwidget)
        self.label_done.setGeometry(QtCore.QRect(1040, 10, 291, 141))
        self.label_done.setScaledContents(True)
        self.label_done.setObjectName("label_done")
        self.label_performance = QtWidgets.QLabel(self.centralwidget)
        self.label_performance.setGeometry(QtCore.QRect(890, 590, 170, 170))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.label_performance.setFont(font)
        self.label_performance.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_performance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_performance.setObjectName("label_performance")
        self.label_text = QtWidgets.QLabel(self.centralwidget)
        self.label_text.setGeometry(QtCore.QRect(820, 550, 380, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_text.setFont(font)
        self.label_text.setScaledContents(True)
        self.label_text.setWordWrap(True)
        self.label_text.setObjectName("label_text")
        self.comboBox_choose_video = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_choose_video.setGeometry(QtCore.QRect(110, 390, 270, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_choose_video.setFont(font)
        self.comboBox_choose_video.setObjectName("comboBox_choose_video")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_start_judge.setText(_translate("MainWindow", "❗Start Judge❗"))
        self.button_choose_video.setText(_translate("MainWindow", "👆🏻 Choose Video 👆🏻"))
        self.label_video_name.setText(_translate("MainWindow", "Video Name: "))
        self.label_interrupt_times.setText(_translate("MainWindow", "Interrupt Times:"))
        self.button_check_result.setText(_translate("MainWindow", "✅Check result✅"))
        self.button_remove_interrupt.setText(_translate("MainWindow", "remove interrupt ❌"))
        self.button_import_result.setText(_translate("MainWindow", "Import Result "))
        self.label_done.setText(_translate("MainWindow", "DoneLabel"))
        self.label_performance.setText(_translate("MainWindow", "A+"))
        self.label_text.setText(_translate("MainWindow", "Perormance: "))
