# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\yipei\主要資料夾\Visual Studio Code Projects\ComputerProjectDesign\0510_ProjectDesign\Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 700)
        Form.setStyleSheet("")
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(375, 50, 450, 80))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.button_choose_video = QtWidgets.QPushButton(Form)
        self.button_choose_video.setGeometry(QtCore.QRect(482, 340, 236, 60))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_choose_video.setFont(font)
        self.button_choose_video.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(100, 100,100);\n"
"border-radius: 20px;\n"
"border: 1px groove gray;\n"
"border-style:outset;")
        self.button_choose_video.setObjectName("button_choose_video")
        self.button_start_judge = QtWidgets.QPushButton(Form)
        self.button_start_judge.setEnabled(True)
        self.button_start_judge.setGeometry(QtCore.QRect(482, 420, 236, 60))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_start_judge.setFont(font)
        self.button_start_judge.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(100, 100, 100);\n"
"border-radius: 20px;\n"
"border: 1px groove gray;\n"
"border-style:outset;\n"
"")
        self.button_start_judge.setObjectName("button_start_judge")
        self.button_plot_result = QtWidgets.QPushButton(Form)
        self.button_plot_result.setGeometry(QtCore.QRect(482, 500, 236, 60))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_plot_result.setFont(font)
        self.button_plot_result.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(100, 100, 100);\n"
"border-radius: 20px;\n"
"border: 1px groove gray;\n"
"border-style:outset;\n"
"")
        self.button_plot_result.setObjectName("button_plot_result")
        self.button_manual = QtWidgets.QPushButton(Form)
        self.button_manual.setGeometry(QtCore.QRect(1120, 630, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_manual.sizePolicy().hasHeightForWidth())
        self.button_manual.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_manual.setFont(font)
        self.button_manual.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_manual.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(195, 195, 195);\n"
"border-radius: 50px;\n"
"border: 1px groove gray;\n"
"border-style:outset;\n"
"")
        self.button_manual.setText("")
        self.button_manual.setObjectName("button_manual")
        self.label_video_name = QtWidgets.QLabel(Form)
        self.label_video_name.setGeometry(QtCore.QRect(525, 200, 150, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_video_name.setFont(font)
        self.label_video_name.setText("")
        self.label_video_name.setScaledContents(True)
        self.label_video_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_video_name.setWordWrap(True)
        self.label_video_name.setObjectName("label_video_name")
        self.label_folder_image = QtWidgets.QLabel(Form)
        self.label_folder_image.setGeometry(QtCore.QRect(515, 140, 170, 170))
        self.label_folder_image.setText("")
        self.label_folder_image.setScaledContents(True)
        self.label_folder_image.setObjectName("label_folder_image")
        self.label_title_image = QtWidgets.QLabel(Form)
        self.label_title_image.setGeometry(QtCore.QRect(800, 30, 111, 101))
        self.label_title_image.setText("")
        self.label_title_image.setScaledContents(True)
        self.label_title_image.setObjectName("label_title_image")
        self.label_title_image_2 = QtWidgets.QLabel(Form)
        self.label_title_image_2.setGeometry(QtCore.QRect(290, 30, 111, 101))
        self.label_title_image_2.setText("")
        self.label_title_image_2.setScaledContents(True)
        self.label_title_image_2.setObjectName("label_title_image_2")
        self.button_manual_2 = QtWidgets.QPushButton(Form)
        self.button_manual_2.setGeometry(QtCore.QRect(1128, 665, 71, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_manual_2.setFont(font)
        self.button_manual_2.setStyleSheet("QPushButton {\n"
"        border: 0px solid;\n"
"    }")
        self.button_manual_2.setObjectName("button_manual_2")
        self.button_check_folder = QtWidgets.QPushButton(Form)
        self.button_check_folder.setGeometry(QtCore.QRect(482, 580, 236, 60))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_check_folder.setFont(font)
        self.button_check_folder.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(100, 100,100);\n"
"border-radius: 20px;\n"
"border: 1px groove gray;\n"
"border-style:outset;")
        self.button_check_folder.setObjectName("button_check_folder")
        self.button_back_menu = QtWidgets.QPushButton(Form)
        self.button_back_menu.setGeometry(QtCore.QRect(800, 600, 60, 60))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.button_back_menu.setFont(font)
        self.button_back_menu.setStyleSheet("QPushButton {\n"
"        border: 0px solid;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(223, 223, 223);\n"
"    }\n"
"")
        self.button_back_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\yipei\\主要資料夾\\Visual Studio Code Projects\\ComputerProjectDesign\\0510_ProjectDesign\\image/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_back_menu.setIcon(icon)
        self.button_back_menu.setIconSize(QtCore.QSize(60, 60))
        self.button_back_menu.setObjectName("button_back_menu")
        self.label_background = QtWidgets.QLabel(Form)
        self.label_background.setGeometry(QtCore.QRect(0, 0, 1200, 700))
        self.label_background.setText("")
        self.label_background.setScaledContents(True)
        self.label_background.setObjectName("label_background")
        self.list_widget_done_folder = QtWidgets.QListWidget(Form)
        self.list_widget_done_folder.setGeometry(QtCore.QRect(415, 160, 370, 510))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.list_widget_done_folder.setFont(font)
        self.list_widget_done_folder.setObjectName("list_widget_done_folder")
        self.label_background.raise_()
        self.label_folder_image.raise_()
        self.label_title.raise_()
        self.button_choose_video.raise_()
        self.button_start_judge.raise_()
        self.button_plot_result.raise_()
        self.button_manual.raise_()
        self.label_video_name.raise_()
        self.label_title_image.raise_()
        self.label_title_image_2.raise_()
        self.button_manual_2.raise_()
        self.button_check_folder.raise_()
        self.button_back_menu.raise_()
        self.list_widget_done_folder.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "鼻腔手術偵測與評價分析"))
        self.label_title.setText(_translate("Form", "鼻腔手術中斷偵測與評價分析"))
        self.button_choose_video.setText(_translate("Form", "👆🏻 選擇資料夾 👆🏻"))
        self.button_start_judge.setText(_translate("Form", "❗開始偵測❗"))
        self.button_plot_result.setText(_translate("Form", "顯示近五次結果圖 📊"))
        self.button_manual_2.setText(_translate("Form", "使用說明"))
        self.button_check_folder.setText(_translate("Form", " 查看已偵測過資料夾 📝"))
